name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
  merge_group:

jobs:
  build-check-test-push:
    uses: HSLdevcom/transitdata-shared-workflows/.github/workflows/ci-cd-typescript.yml@1.0.5
    secrets: inherit
    with:
      checkAndTestOutsideDocker: true
      checkAndTestInsideDocker: true