name: Deploy and test dev

on:
  pull_request:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          repository: HSLdevcom/transitlog-server
          ref: dev
      - name: Build Server and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/transitlog-server
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tags: dev
