name: Deploy and test production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Checkout server
        uses: actions/checkout@v2
        with:
          repository: HSLdevcom/transitlog-server
          ref: production
      - name: Build Server and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/transitlog-server
          username: ${{ secrets.TRANSITLOG_DOCKERHUB_USER }}
          password: ${{ secrets.TRANSITLOG_DOCKERHUB_TOKEN }}
          tags: production
